### ISSUE TITLE
Runs unnecessary validations

### ISSUE THREAD

**Issue by dbaronov** [ederssouza/vanillajs-form-validator#2]
The issue I have is that the vanillajs-form-validator runs the validation on checkbox input type elements at a time when I am not requiring this, as a result I get an error "Cannot read property 'querySelector' of null" once I uncheck all the boxes within the section of the form.

Please advise.

**Comment by ederssouza** [comment]
> The issue I have is that the vanillajs-form-validator runs the validation on checkbox input type elements at a time when I am not requiring this, as a result I get an error "Cannot read property 'querySelector' of null" once I uncheck all the boxes within the section of the form.
> 
> Please advise.

Hello @dbaronov, share your code or repository with me.
